import { Injectable } from '@nestjs/common';
import { randomUUID } from 'crypto';
import { JobWatch, ObservedJob, WatchMatch, WatchRepository, WatchRun } from '../interfaces/watch.types';

@Injectable()
export class InMemoryWatchRepository implements WatchRepository {
  private watches = new Map<string, JobWatch>(); private jobs = new Map<string, ObservedJob>(); private matches = new Map<string, WatchMatch>(); private runs = new Map<string, WatchRun>(); private notifications = new Set<string>();
  async listWatches() { return [...this.watches.values()]; }
  async getWatch(id: string) { return this.watches.get(id) ?? null; }
  async createWatch(input: Partial<JobWatch>) { const now = new Date(); const watch: JobWatch = { id: input.id ?? randomUUID(), name: input.name ?? 'Untitled watch', enabled: input.enabled ?? true, intervalMinutes: input.intervalMinutes ?? 3, timezone: input.timezone ?? 'America/Toronto', sources: input.sources ?? [], sourceTiers: input.sourceTiers ?? {}, companySlugs: input.companySlugs ?? [], companies: input.companies ?? [], searchTerms: input.searchTerms ?? [], requiredTerms: input.requiredTerms ?? [], preferredTerms: input.preferredTerms ?? [], excludedTerms: input.excludedTerms ?? [], locations: input.locations ?? [], countryCodes: input.countryCodes ?? ['CA'], allowedWorkplaceTypes: input.allowedWorkplaceTypes ?? ['remote','hybrid','on-site'], allowedEmploymentTypes: input.allowedEmploymentTypes ?? ['internship','co-op'], minimumScore: input.minimumScore ?? 60, urgentScore: input.urgentScore ?? 80, digestScore: input.digestScore ?? 40, notificationChannels: input.notificationChannels ?? [], initializationMode: input.initializationMode ?? 'baseline', recentWindowMinutes: input.recentWindowMinutes ?? 180, weights: input.weights, createdAt: now, updatedAt: now, ...input } as JobWatch; this.watches.set(watch.id, watch); return watch; }
  async updateWatch(id: string, input: Partial<JobWatch>) { const current = this.watches.get(id); if (!current) throw new Error(`Watch not found: ${id}`); const next = { ...current, ...input, updatedAt: new Date() }; this.watches.set(id, next); return next; }
  async createRun(input: Partial<WatchRun> & { watchId: string }) { const now = new Date(); const run: WatchRun = { id: randomUUID(), startedAt: input.startedAt ?? now, status: 'running', sourcesRequested: [], sourcesSucceeded: [], sourcesFailed: [], jobsFetched: 0, jobsNormalized: 0, newJobsDetected: 0, matchesCreated: 0, notificationsSent: 0, createdAt: now, ...input, watchId: input.watchId }; this.runs.set(run.id, run); return run; }
  async completeRun(id: string, patch: Partial<WatchRun>) { const run = this.runs.get(id); if (!run) throw new Error(`Run not found: ${id}`); const next = { ...run, ...patch }; this.runs.set(id, next); return next; }
  async upsertObservedJob(input: Omit<ObservedJob,'id'|'createdAt'|'updatedAt'>) { const existing = this.jobs.get(input.fingerprint); const now = new Date(); if (existing) { const descriptionChanged = existing.descriptionHash !== input.descriptionHash; const job = { ...existing, ...input, id: existing.id, firstSeenAt: existing.firstSeenAt, updatedAt: now }; this.jobs.set(input.fingerprint, job); return { job, isNew: false, descriptionChanged }; } const job = { ...input, id: randomUUID(), createdAt: now, updatedAt: now }; this.jobs.set(input.fingerprint, job); return { job, isNew: true, descriptionChanged: false }; }
  async upsertMatch(input: Omit<WatchMatch,'id'|'createdAt'|'updatedAt'>) { const key = `${input.watchId}:${input.observedJobId}`; const existing = this.matches.get(key); const now = new Date(); if (existing) { const match = { ...existing, ...input, id: existing.id, firstMatchedAt: existing.firstMatchedAt, updatedAt: now }; this.matches.set(key, match); return { match, isNew: false }; } const match = { ...input, id: randomUUID(), createdAt: now, updatedAt: now }; this.matches.set(key, match); return { match, isNew: true }; }
  async hasNotification(key: string) { return this.notifications.has(key); }
  async recordNotification(input: { idempotencyKey: string }) { this.notifications.add(input.idempotencyKey); }
  async listDigestMatches(watchId: string, min: number, max: number) { return [...this.matches.values()].filter((m) => m.watchId === watchId && m.score >= min && m.score < max).sort((a,b) => b.score-a.score); }
}
