import { Site } from "@ever-jobs/models";
import { JobWatch, WatchSourceTarget } from "../interfaces/watch.types";

const sourceTargets: WatchSourceTarget[] = [
  // Tier 1: direct company career services.
  Site.AMAZON,
  Site.MICROSOFT,
  Site.APPLE,
  Site.NVIDIA,
  Site.STRIPE,
  Site.OPENAI,
  Site.DATADOG,
  Site.DOORDASH,
  Site.COINBASE,
  Site.FIGMA,
  Site.VERCEL,
].map((site) => ({
  site,
  tier: 1 as const,
  intervalMinutes: 3,
  enabled: true,
}));

// Plaid's supported public board is Ashby. Generic ATS targets always carry
// a slug; direct-company wrappers above do not need one.
sourceTargets.push({
  site: Site.ASHBY,
  tier: 1,
  intervalMinutes: 3,
  companySlug: "plaid",
  enabled: true,
});

sourceTargets.push({
  site: Site.CANADAJOBBANK,
  tier: 2,
  intervalMinutes: 15,
  enabled: true,
});

export function defaultInternshipWatch(): Partial<JobWatch> {
  const sources = sourceTargets.map(({ site }) => String(site));
  return {
    name: "Toronto and Canada Software Internships",
    description:
      "Low-latency direct-company and ATS monitoring for Canadian software internships and co-op roles.",
    // Seeding is intentionally safe: initialize the baseline before resume.
    enabled: false,
    intervalMinutes: 3,
    timezone: "America/Toronto",
    sources,
    sourceTargets: sourceTargets.map((target) => ({ ...target })),
    sourceTiers: Object.fromEntries(
      sourceTargets.map(({ site, tier }) => [String(site), tier]),
    ),
    companySlugs: ["plaid"],
    companies: [
      "Google",
      "Amazon",
      "Meta",
      "Shopify",
      "Wealthsimple",
      "Microsoft",
      "Apple",
      "Nvidia",
      "Uber",
      "Stripe",
      "OpenAI",
      "Datadog",
      "DoorDash",
      "Coinbase",
      "Notion",
      "Figma",
      "Ramp",
      "Plaid",
      "Vercel",
      "Netflix",
      "IBM",
      "RBC",
      "TD",
      "Scotiabank",
      "BMO",
      "CIBC",
    ],
    searchTerms: [
      "software engineer intern",
      "software developer intern",
      "software engineering internship",
      "software engineering co-op",
      "software developer co-op",
      "backend engineer intern",
      "backend developer intern",
      "platform engineer intern",
      "infrastructure engineer intern",
      "security engineer intern",
      "cloud engineer intern",
      "devops intern",
      "site reliability engineer intern",
      "full stack developer intern",
      "machine learning engineer intern",
      "data engineer intern",
    ],
    requiredTerms: [
      "intern",
      "internship",
      "co-op",
      "coop",
      "student",
      "university",
      "campus",
      "early career",
    ],
    preferredTerms: [
      "Python",
      "Java",
      "Go",
      "C",
      "C++",
      "JavaScript",
      "TypeScript",
      "SQL",
      "Bash",
      "React",
      "Next.js",
      "Flask",
      "Docker",
      "Docker Compose",
      "Kubernetes",
      "Terraform",
      "GitHub Actions",
      "Google Cloud Platform",
      "Apache Kafka",
      "PostgreSQL",
      "Linux",
      "Auth0",
      "Identity and Access Management",
      "IAM",
      "RBAC",
      "Distributed Systems",
      "Backend",
      "Platform",
      "Cloud",
      "Infrastructure",
      "Security",
      "API",
      "Authentication",
      "Authorization",
    ],
    excludedTerms: [
      "United States only",
      "US only",
      "USA only",
      "must reside in the United States",
      "no Canadian applicants",
      "senior",
      "staff",
      "principal",
      "lead",
      "manager",
      "director",
      "architect",
      "5+ years",
      "7+ years",
      "10+ years",
    ],
    locations: [
      "Toronto",
      "Greater Toronto Area",
      "GTA",
      "Ontario",
      "Canada",
      "Remote Canada",
      "Canada Remote",
    ],
    countryCodes: ["CA"],
    allowedWorkplaceTypes: ["remote", "hybrid", "on-site"],
    allowedEmploymentTypes: ["internship", "co-op"],
    minimumScore: 60,
    urgentScore: 80,
    digestScore: 40,
    notificationChannels: [{ type: "discord", destinationRef: "default" }],
    initializationMode: "baseline",
    recentWindowMinutes: 180,
    nextRunAt: null,
  };
}
