import { Inject, Injectable, Logger } from '@nestjs/common';
import { JobPostDto } from '@ever-jobs/models';
import { JobWatch, ObservedJob, WatchRepository, WatchSourceExecutor } from '../interfaces/watch.types';
import { JobFingerprintService } from './job-fingerprint.service';
import { JobScoringService } from './job-scoring.service';
import { NotificationDispatcher } from './notification-dispatcher.service';
export const WATCH_SOURCE_EXECUTOR = Symbol('WATCH_SOURCE_EXECUTOR');
@Injectable()
export class WatchExecutionService { private readonly logger = new Logger(WatchExecutionService.name); private locks = new Set<string>(); constructor(@Inject('WatchRepository') private repo: WatchRepository, private fp: JobFingerprintService, private scoring: JobScoringService, private notifications: NotificationDispatcher, @Inject(WATCH_SOURCE_EXECUTOR) private executor: WatchSourceExecutor) {}
  async runWatch(watchId: string, mode?: 'baseline'|'recent-only'|'notify-all') { if (this.locks.has(watchId)) throw new Error(`Watch already running: ${watchId}`); this.locks.add(watchId); const startedAt = new Date(); const watch = await this.repo.getWatch(watchId); if (!watch) throw new Error(`Watch not found: ${watchId}`); const run = await this.repo.createRun({ watchId, startedAt, sourcesRequested: watch.sources }); let jobs: JobPostDto[] = []; let notificationsSent = 0; let newJobs = 0; let matchesCreated = 0; const initMode = mode ?? (watch.initializedAt ? 'notify-all' : watch.initializationMode); try { const batches = await Promise.allSettled(watch.searchTerms.map((searchTerm) => this.executor.search({ watch, searchTerm, sources: watch.sources }))); const succeeded: string[] = []; const failed: string[] = []; for (const r of batches) r.status === 'fulfilled' ? jobs.push(...r.value) : failed.push(String((r as PromiseRejectedResult).reason?.message ?? 'source failure')); succeeded.push(...watch.sources.filter(Boolean)); for (const job of jobs) { const observed = this.toObserved(job); const upsert = await this.repo.upsertObservedJob(observed); if (upsert.isNew) newJobs++; const breakdown = this.scoring.score(job, watch); const matchUpsert = await this.repo.upsertMatch({ watchId, observedJobId: upsert.job.id, score: breakdown.total, scoreBreakdown: breakdown, matchedTerms: breakdown.matchedKeywords, excludedReason: breakdown.exclusionReason, status: 'new', firstMatchedAt: new Date(), lastMatchedAt: new Date(), notificationState: 'pending' }); if (matchUpsert.isNew) matchesCreated++; if (this.shouldNotify(initMode, upsert.isNew, breakdown.total, watch, job)) { const type = breakdown.total >= watch.urgentScore ? 'urgent' : 'standard'; notificationsSent += await this.notifications.dispatch({ idempotencyKey: '', type, watch, job: upsert.job, match: matchUpsert.match, detectedAt: new Date() }); } }
      const completedAt = new Date(); await this.repo.updateWatch(watch.id, { initializedAt: watch.initializedAt ?? completedAt, lastRunAt: completedAt, nextRunAt: new Date(completedAt.getTime() + watch.intervalMinutes * 60000) }); return this.repo.completeRun(run.id, { status: failed.length ? 'partial' : 'completed', completedAt, sourcesSucceeded: succeeded, sourcesFailed: failed, jobsFetched: jobs.length, jobsNormalized: jobs.length, newJobsDetected: newJobs, matchesCreated, notificationsSent, durationMs: completedAt.getTime() - startedAt.getTime() }); } catch (e: any) { this.logger.error(`watch ${watchId} failed: ${e.message}`); return this.repo.completeRun(run.id, { status: 'failed', completedAt: new Date(), errorSummary: e.message, durationMs: Date.now() - startedAt.getTime() }); } finally { this.locks.delete(watchId); } }
  private shouldNotify(mode: string, isNew: boolean, score: number, watch: JobWatch, job: JobPostDto) { if (score < watch.minimumScore) return false; if (mode === 'baseline') return false; if (mode === 'recent-only') { const posted = job.datePosted ? new Date(job.datePosted).getTime() : Date.now(); return Date.now() - posted <= (watch.recentWindowMinutes ?? 180) * 60000; } return isNew || mode === 'notify-all'; }
  private toObserved(job: JobPostDto): Omit<ObservedJob,'id'|'createdAt'|'updatedAt'> { const loc = typeof job.location === 'string' ? job.location : [job.location?.city, job.location?.state, job.location?.country].filter(Boolean).join(', '); return { fingerprint: this.fp.fingerprint(job), source: String(job.site ?? 'unknown'), sourceType: job.atsType ?? null, externalJobId: job.id ?? job.atsId ?? null, company: job.companyName ?? null, normalizedCompany: this.fp.normalizeText(job.companyName), title: job.title, normalizedTitle: this.fp.normalizeText(job.title), location: loc || null, normalizedLocation: this.fp.normalizeLocation(loc), workplaceType: job.isRemote ? 'remote' : job.workFromHomeType ?? null, employmentType: job.employmentType ?? job.jobType?.join(',') ?? null, description: job.description ?? null, descriptionHash: this.fp.descriptionHash(job.description), jobUrl: job.jobUrl, applicationUrl: job.applyUrl ?? job.jobUrlDirect ?? null, sourcePublishedAt: job.datePosted ? new Date(job.datePosted) : null, firstSeenAt: new Date(), lastSeenAt: new Date(), rawPayload: job }; }
}
